#!/bin/bash

# Shamelessly stolen from http://stackoverflow.com/a/246128/889949
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done

exec $(which php) $(cd -P "$( dirname "$SOURCE" )" && pwd)"/distil.php" "$@"
