#!/usr/bin/php
<?php

namespace WSDLDistiller;

spl_autoload_register(function ($className) {
    if (substr($className, 0, 13) === 'WSDLDistiller') {
        $file = __DIR__ . '/' . strtr($className, '\\', '/') . '.php';

        if (is_file($file)) {
            /** @noinspection PhpIncludeInspection */
            require $file;
        }
    }
});

function error($message)
{
    fwrite(STDERR, "Error: $message\n");
    exit(1);
}

function write($format, $name, $data)
{
    $file = sprintf($format, $name);

    echo "Writing {$file}...";
    echo file_put_contents($file, $data) === strlen($data) ? 'done' : 'failed';
    echo "\n";
}

function render_template($template, $vars)
{
    return preg_replace_callback('/@@(?=@*+{)|@{|{(\w+)}/', function($match) use($vars) {
        if ($match[0][0] === '@') {
            return $match[0][1];
        }

        return isset($vars[$match[1]]) ? $vars[$match[1]] : $match[0];
    }, $template);
}

function parse_options($argv, &$options)
{
    $phpIdentifier = '[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*';

    for ($i = 1, $l = count($argv); $i < $l; $i++) {
        $parts = explode('=', $argv[$i], 2);
        $value = count($parts) === 2 ? $parts[1] : NULL;
        $opt = strtolower(trim($parts[0], '-'));

        switch ($opt) {
            case 'prefix':
                if ($value === NULL) {
                    $value = $argv[++$i];
                }

                if (!preg_match("/^$phpIdentifier$/", $value)) {
                    error("Invalid class name prefix");
                }
                break;

            case 'namespace':
                if ($value === NULL) {
                    $value = $argv[++$i];
                }

                if (!preg_match("/^$phpIdentifier(?:\\\\$phpIdentifier)*$/", $value)) {
                    error("Invalid namespace identifier");
                }
                break;

            case 'file-names':
                if ($value === NULL) {
                    $value = $argv[++$i];
                }

                if (substr_count($value, '%s') !== 1) {
                    error('Invalid file naming pattern, must contain "%s" exactly once');
                }
                break;

            case 'output-dir':
                if ($value === NULL) {
                    $value = $argv[++$i];
                }
                break;

            default:
                error("Unknown option: $opt");
        }

        $options[$opt] = $value;
    }
}

$options = [
    'prefix'     => NULL,
    'namespace'  => NULL,
    'file-names' => '%s.php',
    'output-dir' => __DIR__ . DIRECTORY_SEPARATOR . 'wsdl_classes',
];

$fileName = basename(__FILE__);
$helpStr = <<<HELP

 Syntax: php {$fileName} [options] <wsdl-path>
  Options:
    --prefix      Prefix all class names with this string
    --namespace   Place generated files in this namespace
    --file-names  Pattern for naming files (printf with one string argument)
    --output-dir  Directory where generated files will be created

HELP;

if (!isset($argv[1])) {
    exit($helpStr);
}

if (!$wsdlPath = @realpath(array_pop($argv))) {
    error("Invalid WSDL path");
}

parse_options($argv, $options);

if (!file_exists($options['output-dir'])) {
    @mkdir($options['output-dir'], 0777, TRUE);
}
if (!is_dir($options['output-dir']) || !($options['output-dir'] = realpath($options['output-dir']))) {
    error('Output directory does not exist and it could not be created');
}

$pathFormat = rtrim($options['output-dir'], '\\/') . DIRECTORY_SEPARATOR . $options['file-names'];

$namespace = isset($options['namespace']) ? "\nnamespace {$options['namespace']};\n" : '';
$version = date('Y.m.d.His');
$fileHeader = <<<HEADER
<?php
/**
 * This file was automatically generated by WSDLDistiller and should not be altered
 * @see https://github.com/DaveRandom/WSDLDistiller
 * @version {$version}
 */
{$namespace}

HEADER;

$baseTypeTemplate = file_get_contents(__DIR__ . '/WSDLDistiller/Types/WSDLDistillerBaseType.php');
write($pathFormat, 'WSDLDistillerBaseType', render_template($baseTypeTemplate, ['NAMESPACE' => $namespace]));

$distiller = new Distiller($wsdlPath, $options['prefix'], $options['namespace']);
foreach ($distiller->getClasses() as $class) {
    write($pathFormat, $class->getName(), $fileHeader . $class);
}

$serviceCollection = $distiller->getServiceCollection();
write($pathFormat, $serviceCollection->getBaseServiceName(), $fileHeader . $serviceCollection->getBaseServiceCode());
foreach ($serviceCollection->getServices() as $service) {
    write($pathFormat, $service->getClassName(), $fileHeader . $service);
}

write($pathFormat, $serviceCollection->getServiceFactoryName(), $fileHeader . $serviceCollection->getServiceFactoryCode());
